# Site settings
title: Broseley Camera Club
email: BroseleyPhotography@gmail.com
description: We are a friendly bunch of amateur photography enthusiasts, meeting once a month with a range of practical tips and helpful advice.

baseurl:  http://www.broseleycameraclub.org
url:  http://www.broseleycameraclub.org


# Build settings
markdown: kramdown

highlighter: rouge



# Pagination
paginate: 5
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  programme:
    output: true
    permalink: /programme/:path/


