# Site settings
title: Broseley Camera Club
email: BroseleyPhotography@gmail.com
description: We are a friendly bunch of amateur photography enthusiasts, meeting once a month with a range of practical tips and helpful advice.
# logo: "/assets/img/BCC-Logo.webp"

baseurl:
url: 
  
# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins: 
- jekyll-paginate
# - jekyll-exif-data


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  programme:
    output: true
    permalink: /programme/:path/
  featured:
    output: true
    permalink: /featured/:path/
  onlinecomps:
    output: true
    permalink: /onlinecomps/:path/



